
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goshelly
  labels:
    app: goshelly
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goshelly
  template:
    metadata:
      labels:
        app: goshelly
    spec:
      containers:
      - name: goshelly
        image: arorasoham9/goshelly:fileExec
        imagePullPolicy: Always
        env:
        - name: EMAIL_ID
          value: ""
        - name: CHANNEL_ID
          value: ""
        - name: SLACK_BOT_TOKEN
          value: ""
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"